version: '3'
services:
  mysql:
    build: ./sql 
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=strongpassword
      - MYSQL_DATABASE=whaticket
      - MYSQL_USER=whaticket
      - MYSQL_PASSWORD=whaticket
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "exit 0"
    networks:
      - app-network
      
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - BACKEND_URL=http://localhost
      - PROXY_PORT=8080
      - PORT=8080
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=strongpassword
      - DB_NAME=whaticket
      
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/

networks:
  app-network:
    driver: bridge


